"""Analysis helpers for the Extended Criticality modular model."""

from .avalanches import avalanche_table, fit_power_law
from .fig5_workflow import (
    ROUND1_E0_VALUES,
    FitTargets,
    analyze_avalanche_groups,
    build_jij_metadata,
    build_campaign_manifest,
    build_refinement_e0_values,
    build_seed_series,
    campaign_run_name,
    canonical_e0_label,
    connection_cache_name,
    connection_cache_filename,
    detect_best_sigma,
    load_avalanches_from_runs,
    load_jij_metadata,
    load_manifest,
    load_run_timings,
    load_runtime_record,
    manifest_run_dirs,
    materialize_cached_jij,
    memory_signature,
    parse_run_spec,
    pooled_groups_from_manifest,
    resolve_fit_label,
    pool_avalanche_groups,
    prepare_learning_seed,
    prepare_reuse_seed,
    run_prepared_simulation,
    save_jij_metadata,
    save_manifest,
    save_runtime_record,
    summarize_runtime_table,
    summarize_campaign,
    validate_jij_metadata,
)
from .io import (
    find_start_file,
    find_output_file,
    load_medie,
    load_q,
    load_rate,
    load_spikes,
    load_start,
    read_seed,
)
from .metrics import flexibility, module_isi_cv, summarize_run
from .runner import run_simulation
from .seeds import make_parameter_sweep, write_seed

__all__ = [
    "avalanche_table",
    "find_start_file",
    "find_output_file",
    "flexibility",
    "fit_power_law",
    "FitTargets",
    "ROUND1_E0_VALUES",
    "load_medie",
    "load_q",
    "load_rate",
    "load_spikes",
    "load_start",
    "load_avalanches_from_runs",
    "load_jij_metadata",
    "load_manifest",
    "load_run_timings",
    "load_runtime_record",
    "make_parameter_sweep",
    "materialize_cached_jij",
    "memory_signature",
    "parse_run_spec",
    "pooled_groups_from_manifest",
    "resolve_fit_label",
    "pool_avalanche_groups",
    "build_campaign_manifest",
    "build_refinement_e0_values",
    "build_seed_series",
    "campaign_run_name",
    "canonical_e0_label",
    "detect_best_sigma",
    "manifest_run_dirs",
    "module_isi_cv",
    "prepare_learning_seed",
    "prepare_reuse_seed",
    "read_seed",
    "run_prepared_simulation",
    "run_simulation",
    "save_jij_metadata",
    "save_manifest",
    "save_runtime_record",
    "summarize_runtime_table",
    "summarize_campaign",
    "summarize_run",
    "analyze_avalanche_groups",
    "build_jij_metadata",
    "connection_cache_name",
    "connection_cache_filename",
    "validate_jij_metadata",
    "write_seed",
]
